spring.datasource.url=jdbc:h2:mem:repositorytestdb;MODE=MySQL;NON_KEYWORDS=DAY;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=create-drop
# init.mode=neverを指定しているため、data.sqlは実行されずに、
# 各RepositoryTestごとの@SetupにRepositoryで使われる
# テストデータの作成を一任させる。
# こうしないと、data.sqlと@Setupで2回同じデータを入れてしまうため、
# 一意性制約に引っかかってしまう。
# テスト毎に、毎回insertをdata.sqlではなく、
# RepositoryTestの@SetUp()からテーブルを作成するため、H2でのテストデータの作成は行わない。
# テストごとにテーブルを作成するため、test.propertiesとは異なり、
# ddl-autoはcreate-dropにしている。
# spring.jpa.defer-datasource-initialization=true